### ISSUE TITLE
Keyer is clipping dits at higher speeds 

### ISSUE THREAD

**Issue by ve3ids** [df8oe/mchf-github#1073] opened 2017-09-15 12:21 UTC
In the recent builds, the keyer is clipping dits at speeds over 20 WPM. I have went back to .57 and it works great there. Version 6 hardware. 

73 Don ve3ids

**Comment by db4ple** [comment] 2017-09-15 18:28
Hi,
you could help us a great deal if you would try to identify the last working release.
It should be easy and requires about 6 firmwares to be loaded if you go by a method called binary search:
We know 57 is not affected and 97 is. So you test (98 - 57)/2 + 57 = 41/2 + 57 = 77.5 -> 
If 77 does not have the problem it came in between 98 and 77 -> (98 - 77)/2 + 77 = 21/2 + 77 = 87.5 
if 87 does have the problem the answer is in between  87 and 77 -> (87 - 77)/2 + 77 = 82 
if 82 has it ....
You get the idea. So you will find quickly the right binary with the help of a little math.
Once that is done carefully, we have found the problematic commit and can start looking into the cause with much less work.

TU,
Danilo

**Comment by ve3ids** [comment] 2017-09-15 20:05
Hi Danilo,

Thanks for the interest. I have run through the commits and .84 seems to be
the problem. Up to and including .72 the keyer works perfectly. At .73, it
locks in tx mode, not actually transmitting but the display is frozen and I
have to cut the dc to turn it off. This happens through .83. At .84
forward, the keyer will clip the first dit in a letter at higher speeds. 72
is the last stable commit to not lock up and after 83, clip the start of
the transmission.
Hope this helps. Good luck!

72 Don VE3IDS

**Comment by db4ple** [comment] 2017-09-15 21:28
Thanks,
I hope this narrows it down for us (and you). 
@phaethon: Please consider this issue, seems to be related to the cw_keyer changes.

**Comment by phaethon** [comment] 2017-09-16 04:59
@ve3ids what keyer mode do you use? Does it start transmitting after a small delay (i.e. not transmitting the start thus clipping it) or it starts transmitting right away with a shorter dit?

**Comment by s53dz** [comment] 2017-09-16 08:29
To my view the clipping of **the first dit** is happening at all speeds, notable from 10 to 48 WPM. **But not always!** As I can tell the issue is worst at a very-very short touch of a paddle. I can confirm that it happens to the first one also when a train of dots is produced. 

The reason for this could also be in the anti-bouncing measures not being strong enough.

I have measured the signal at the TX mixer output. (D2.5.98)
**EDIT:**  Using internal keyer.
**EDIT2:** As far as I can see the TX starts immediately but the beginning of a first dot is cut. 
**EDIT3:** It is also notable that the ON slope of a RF dot is very steep in this case and not the same as shape of a complete normal dot at ON/OFF.

73 Bojan

**Comment by ve3ids** [comment] 2017-09-16 10:58
I use iambic A mode. I am not sure whether it is the transmitter being
delayed in starting or not but that would be my guess but I am not an
expert by any measure. It sounds like if you had a dirty contact in a key
but only on the first dit. This is the same effect that the straight key or
external keyer has only with those it is much much worse.

72 Don ve3ids

On Sep 16, 2017 12:59 AM, "Eriks Dobelis" <notifications@github.com> wrote:

@ve3ids <https://github.com/ve3ids> what keyer mode do you use? Does it
start transmitting after a small delay (i.e. not transmitting the start
thus clipping it) or it starts transmitting right away with a shorter dit?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/df8oe/UHSDR/issues/1073#issuecomment-329946050>, or mute
the thread

**Comment by phaethon** [comment] 2017-09-19 09:04
@ve3ids , please, check the latest code

**Comment by ve3ids** [comment] 2017-09-19 11:32
Ericks

I tried .104 last night and it was improved but still randomly clips a few
first dits. I will try .105 tonight after I get home from work. Thanks for
your efforts!

73 Don ve3ids




On Sep 19, 2017 5:04 AM, "Eriks Dobelis" <notifications@github.com> wrote:

@ve3ids <https://github.com/ve3ids> , please, check the latest code

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/df8oe/UHSDR/issues/1073#issuecomment-330477017>, or mute
the thread

**Comment by s53dz** [comment] 2017-09-19 14:40
D2.5.105,
My short report: All first dots in my case are clean now.
However, when testing the first dot I managed to "hang" mcHF on TX (PTT is holding but no RF output) with one really quick touch of the dot or dash paddle. But it is back to normal with the next CW element. For me this is ok since it does not happen at normal work.

TNX 73 Bojan

**Comment by db4ple** [comment] 2017-09-19 20:10
Nothing beats measurements: I measured the output of 2.5.103 and 2.5.105 at 40 WPM (Iambic, measure via second receiver).
2.5.103: First dit 26ms, second dit  31.25
2.5.103 First dit 31ms, second dit 31.25 
40 WPM  translate to exactly 30ms dit according to the formula, but we have slightly longer dit and a slightly shorter pause, so everything is back to normal.

I would say, we can close this issue now.

**Comment by ve3ids** [comment] 2017-09-19 22:46
I just tested the internal keyer. It is back, it works great again! Thanks
very much for your work and expertise, much appreciated. I am assuming this
is unrelated to the straight key/external keyer support? #1011?

Thanks again and 73
Don ve3ids



On Sep 19, 2017 4:11 PM, "db4ple" <notifications@github.com> wrote:

Nothing beats measurements: I measured the output of 2.5.103 and 2.5.105 at
40 WPM (Iambic, measure via second receiver).
2.5.103: First dit 26ms, second dit 31.25
2.5.103 First dit 31ms, second dit 31.25
40 WPM translate to exactly 30ms dit according to the formula, but we have
slightly longer dit and a slightly shorter pause, so everything is back to
normal.

I would say, we can close this issue now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/df8oe/UHSDR/issues/1073#issuecomment-330659164>, or mute
the thread

**Comment by s53dz** [comment] 2017-09-20 08:38
> Nothing beats measurements: I measured the output of 2.5.103 and 2.5.105 at 40 WPM (Iambic, measure via second receiver).
> 2.5.103: First dit 26ms, second dit 31.25
> 2.5.103 First dit 31ms, second dit 31.25
> 40 WPM translate to exactly 30ms dit according to the formula, but we have slightly longer dit and a slightly shorter pause, so everything is back to normal.

This is of course very nice measurement and straight forward result, but when I tested it I realized that some individual first dots were differently cut resulting in their different length. And **this issue is gone for me**, which is great.

73 Bojan

**Closed as completed** 2017-09-22 00:30 UTC
Labels: bug
