### ISSUE TITLE
Big Trouble with output

### ISSUE THREAD

**Issue by WD8BXS** [df8oe/mchf-github#741] opened 2017-01-13 01:50 UTC
I got an email from a fellow who said he heard me on 40 and I was 30+ KC wide.
I hooked up with a friend 5 miles away, and here is a picture of my signal on 40 meters and 20 meters.

20 Meters
![image](https://cloud.githubusercontent.com/assets/25059155/21915511/4d46f9d0-d908-11e6-88d7-1cff19e24b00.png)
All of these lobes are coming from the mcHF

And now 40 the down arrows show the width, and the other arrows show the two lobes of equal strength that the mcHF is puttin out on 40.
![image](https://cloud.githubusercontent.com/assets/25059155/21915557/9a5fd69c-d908-11e6-87ce-ab037e135484.png)

We also checked other bands with similar results.

I have not done the T7 mod yet, will that help with this spurious emission??

Chuck

**Comment by df8oe** [comment] 2017-01-13 06:34
Your output may be overdriven, or PIN diode switching does produce spurious signals. I guess it is PIN diode switching...

Sadly at the moment this modification is only available at our German Project Group website. I will have a look if I can translate it today and put it to the WIKI.

73
Andreas

**Comment by df8oe** [comment] 2017-01-13 06:52
I have translated to modifications page of WIKI:

https://github.com/df8oe/mchf-github/wiki/Recommended-Modifications#ui-0405-h-029

You can test if PIN diode switching is the reason by removing C78 on RF board. If sputious disappear PIN diode switching is the cause. ATTENTION: When removing C78 only TX does work. For testing in QSO you have to use a seperate receiver to listen to your partner ;)

73
Andreas

**Comment by s53dz** [comment] 2017-01-13 07:54
Andreas, 

it should be labeled with RF not UI.

73 Bojan S53DZ

**Comment by df8oe** [comment] 2017-01-13 08:00
You can help us if you correct small typos like this by yourself ;)

**Comment by DG9BFC** [comment] 2017-01-13 08:50
for me the humps every 12 kc looks like not well calibrated iq correction ....

**Comment by df8oe** [comment] 2017-01-13 10:46
...or a disturbed iq signal path (one of the LO signals missing or crippled, one of the four iq audio signals missing or crippled).

**Comment by WD8BXS** [comment] 2017-01-13 12:13
I have tried the IQ correction, but I see no change at all, this could be because of the spurious emission. Maybe after I get the pin diodes fixed the IQ will work better.

**Comment by WD8BXS** [comment] 2017-01-13 12:18
Interesting, the number of humps changes with the RX/TX translation value!!

**Comment by df8oe** [comment] 2017-01-13 12:18
Hi Chuck,

dont do "shots in the dark" - step forward logical...

First measure if both LO mixing signals reach TX mixer with same amplitude. That is a MUST.
Then measure the four audio-IQ-signals which go into TX mixer (use TUNE mode). They must have same amplitude. You can use oscilloscope - and test at a low band (80m or 160m) because of oscilloscope is working there even if its a cheap or old one.

If both is correct, remove C78 and look if distrotions are gone or not. If not (and you do not have idea how to go on) ask again.

Good luck
Andreas

**Comment by df8oe** [comment] 2017-01-13 12:19
I am nearly sure your IQ signal path is broken at some part (LO or audio).

73
Andreas

**Comment by WD8BXS** [comment] 2017-01-13 12:31
OK, are the four audio IQ signal lines labeled TXE_0, TXE_180, TXE_90,TXE_270 ??

Which are the two LO mixing signals??  TX_CLK_P  and TX_CLK_N  ???

**Comment by df8oe** [comment] 2017-01-13 12:38
Correct in both :) On my old 0.4 schematics LO clock is labeled tx_0 and TX_90

**Comment by WD8BXS** [comment] 2017-01-13 13:19
Some Progress my friend, in inspecting the board I found R71 NOT soldered on one side. 
Output looking much better, IQ adjustment still has no effect.
 I will move on to the testing you suggested.

**Comment by df8oe** [comment] 2017-01-13 13:22
IQ adjustment is very sensible and you must follow instructions otherwise you are failing 100%. Please follow instructions 
https://github.com/df8oe/mchf-github/wiki/Adjustment-and-Configuration-Manual#iq-calibration

...before you are looking for an issue what no longer exists...

**Comment by WD8BXS** [comment] 2017-01-13 13:58
Both LO mixing signals equal, all four IQ signals equal.

**Comment by df8oe** [comment] 2017-01-13 14:53
OK - sounds good. Now start calibrating IQ according to link in my last post. If it is working you must be able to suppress the signal which is described in manual down to the noise floor.

**Comment by WD8BXS** [comment] 2017-01-13 14:59
OK, have to go to work, will continue later, Thanks

**Comment by WD8BXS** [comment] 2017-01-13 15:02
Sure would like to see a video of this procedure!

**Comment by df8oe** [comment] 2017-01-13 15:03
have a nice day!

**Comment by WD8BXS** [comment] 2017-01-13 21:32
OK, I think I did the IQ adjustments, I did hear a slight tone and got it to go away..
Here are two screen shots, one with C78 IN and one with C78 out, First with C78 in.

![image](https://cloud.githubusercontent.com/assets/25059155/21946268/a3b50aa0-d9ad-11e6-9b91-392a9e77cb2e.png)

Now C78 Out

![image](https://cloud.githubusercontent.com/assets/25059155/21946289/bb333332-d9ad-11e6-9339-59aeeb173d96.png)



Looking at this mod next:  http://www.m0nka.co.uk/?p=5545

**Comment by WD8BXS** [comment] 2017-01-13 22:32
Hmmmm, I have C78 out but still have receive!!!

**Comment by df8oe** [comment] 2017-01-14 08:14
You see PIN diode switching causes distortions. I think it's the best to fit relay instead of it.
If C78 is removed RX input path is broken. All you hear are very strong signals which are coupling via wires and PCB capacities.

**Comment by WD8BXS** [comment] 2017-01-14 15:31
Yes, I see that.  Where is the proper Schematic for installing the relay?
And I am told that the "Long time in PiplineTX Mod" will fix the extra humps.
http://www.m0nka.co.uk/?p=5545#comment-192171

**Comment by df8oe** [comment] 2017-01-14 15:45
I have added link for getting bigger schematics to WIKI (positioned under embedded small schematics).

**Comment by df8oe** [comment] 2017-01-14 15:53
Because of its not a software related issue I close this now. It is not listed in the active issue list furthermore - but it is still existent and you can write comments and read the existing.

**Closed as completed by df8oe** 2017-01-14 15:53 UTC
Labels: bug
