### ISSUE TITLE
starting cat switches vfo to blue colour

### ISSUE THREAD

**Issue by DG9BFC** [df8oe/mchf-github#338] opened 2016-05-01 12:26 UTC
when i start hdsdr (means cat in engaged) then in the same second the vfo change to blue

turning vfo in mchf just 1 hz up or down and it is white again

turning vfo in sdr soft in 10 hz steps most of the commands switch also vfo to blue but turns to white after very short moment ... sometimes stays blue

tested in 49m band (radio darc)

**Comment by db4ple** [comment] 2016-05-05 08:32
Have to check that. Blue VFO color should not stay, even in CAT mode.

**Comment by db4ple** [comment] 2016-05-06 14:08
Currently I cannot reproduce the blue color, is it only in HDSDR (haven't tested this yet) or in all CAT tools (I tested wsjtx and fldigi, no problems).

Thanks, 
Danilo

**Comment by DG9BFC** [comment] 2016-05-06 18:32
when i start hdsdr it switches to blue ... and also when starting 
commander (to use with multipsk) ... did not check other soft yet

dg9bfc

sigi

Am 06.05.2016 um 14:08 schrieb db4ple:

**Comment by DL3NCW** [comment] 2016-05-07 15:33
Also happens occasionally to me if i use HRD V5.x transfering
a frequency from the database into the mchf

**Comment by db4ple** [comment] 2016-05-13 10:10
We disabled the blue digits for now. However, we did not look into the root cause for the blue color staying. However, if it stayed it meant that the desired frequency was set. Otherwise color would have changed. So we may close this issue from my point of view or keep it.

**Comment by df8oe** [comment] 2016-05-13 13:00
never could reproduce...

vy 73
Andreas

**Closed as completed by df8oe** 2016-05-13 13:00 UTC

**Comment by DG9BFC** [comment] 2016-05-13 14:42
with a version that has the blue digits active ... it was always with 
power on of hdsdr ...
every first cat switched to blue

turning dial or change qrg in hdsdr and numbers are white again

cause you now have the blue numbers not active i do not have that 
"fault" anymore ... it is maybe a small software glitch or similar thing 
... seems as polling qrg from hdsdr does switch to blue ... but as 
reported ... now i do not have it in this version cause you disengaged 
the blue numbers ...

greetz

sigi

ps ... i could show it to you with an older version ... just in case you 
wanna look for it

Am 13.05.2016 um 13:00 schrieb DF8OE:
