### ISSUE TITLE
FreeDV after 10-15 min , stops!

### ISSUE THREAD

**Issue by ly2bok** [df8oe/mchf-github#595] opened 2016-10-07 06:28 UTC
Hi,
All  about “FreeDV” is a new thing for us and is very interesting. A sincere thank you for the work done.
We believe that our test results may be useful for you in the nearest future.
Some of our impressions after FreeDV test.
In tests we conducted with three mcHF transceivers. 
The results of all three was similar:
1.   After about 10 - 15 minutes FreeCD work, transceivers work stops: PTT does not work, spectrum image becomes jerky. If you rotate the main knob, frequency numbers "stain" in red. Again to return to normal starting position is possible only by restarting the transceiver.
2.   By switching to a different type mode (SSB or CW), the screen remains unnecessary FreeDV information: "teaser" line and BER = 0.128.
3.  When you select FreeDV, the word "DIGITAL" in the lower left corner of the display changes to yellow "FreeDV”. After returning to a different type of work, "FreeDV” remains, but its color now is blue. We do not know whether such "DIGITAL" and "FreeDV" alternation is normal, or not?
73 from LY3BD, LY2BOK, LY3BFN, Lithuania.

**Comment by db4ple** [comment] 2016-10-07 06:55
Hi Guys,

thanks for testing FreeDV at mcHF. Item 1) is a duplicate of #589, and a fix has been integrated 2) is fixed in last daily build, and 3) is intended to be like this. The blue box shows that last activated digital mode. This will make more sense in future if we support multiple digital modes.

Please close this issue. Thank you,
Danilo

**Closed as completed** 2016-10-13 06:36 UTC
