### ISSUE TITLE
FreeDV: Problem with 'red frequency' after longer use

### ISSUE THREAD

**Issue by dm6tt** [df8oe/mchf-github#589] opened 2016-10-05 20:10 UTC
I tested freedv the last days and mcHF was running a longer time in freedv enabled.
After approx. 30min the frequency is displayed in red after switching the band.

In Detail:
- switch on and tune to the received frequency
- switch on freedv
- wait >30min
  -switch band (+ or -)
  -> frequency is displayed red, must restart the transceiver.

73, Marcus, DM6TT

**Comment by db4ple** [comment] 2016-10-05 20:14
Hi,

thank you for reporting. Well, this is a known issue from now on. I and all others who tried FreeDV experienced the same (but did not put into an issue, even I did not :-( )
However, I've been thinking about this issue already and have a hunch what it could be.

**Comment by db4ple** [comment] 2016-10-06 08:44
Hi,
it seems that my hunch was right. Switching off the temperature correction (TXCO == Stopped) causes this issue to disappear. I have to verify if it is caused by the temp sensor code or by the Si570 code interaction. Will take a while I guess, since I have no immediate idea and testing involves waiting for long periods of time.

**Comment by dm6tt** [comment] 2016-10-07 13:33
Still get the 'red frequency' with the actual version after a while.
There is some activity in the waterfall, but I don't know if it is only a colour issue.

Marcus

**Comment by db4ple** [comment] 2016-10-07 13:40
Hi,
yes, it seems that the fix does not solve the issue all the time. It seems, we need to dig deeper to find the root cause for the I2C bus lockup. Will take a while.

We'll use the issue comments to keep everyone up to date.

**Comment by db4ple** [comment] 2016-10-17 06:38
Hi,
due to the nature of the problem it takes some time to make progress. The issue seems to be connected to the duration of the interrupt. If we run the "normal" analog demodulator in addition to the digital demodulator (this makes the interrupt taking much, much longer time), the I2C never looks up. In the digital modes, the interrupt does not do much besides copying a few bytes around so it is done in a few microseconds as opposed to several hundreds of them. It seems that this interrupt short duration somehow causes the problem. But why, no idea at the moment.

**Comment by df8oe** [comment] 2016-12-04 16:24
for now this is fixed via workaound. Maybe a "perfect" soultion another time :)

**Closed as completed by df8oe** 2016-12-04 16:24 UTC
Labels: bug
