### ISSUE TITLE
Tune Power

### ISSUE THREAD

**Issue by ghost** [df8oe/mchf-github#330] opened 2016-04-28 20:09 UTC
Firmware Stand vom : 28.04.2016 11:39:28

Hi,

from my point of view there is no tune-power in the 60m, 15m, 12m and 10m band.

73, Wolfgang
DL2KI

**Comment by df8oe** [comment] 2016-04-29 05:54
Hopefully fixed (only reproducable on some mcHFs - not on one of our testing devices)

vy 73
Andreas

**Comment by ghost** [comment] 2016-04-29 10:35
Hi,

trying out the current DS, I have found that the missing tune power for me depends on the frequency.
- 3511kHz no power, even as 7.011kHz, 10 111kHz, 14.011kHz, ...
  setting in the PWR adjust menu brown
- 3512kHz and up, output power OK, even as 7.012kHz, 10.112kHz, 14.012kHz, ...
  setting in the PWR adjust menu white

73, Wolfgang
DL2KI

**Comment by db4ple** [comment] 2016-04-30 08:13
Hi,
thanks for reporting this. Issue was stricter checking of TX power values. Unfortunately not the TX frequency was used but the IQ center frequency (which can offset +/- 12khz). And depending on your settings 3511 - 12 -> 3499 -> outside ham band -> no TX power settings -> no power. You get the idea. Fix is being prepared.

To test:
If you change the translation offset, the frequency will change to 3505/3506 or to the top of the band.

**Comment by ghost** [comment] 2016-04-30 09:45
Hi Danilo,

fine. My "RX/TX Freq Xlate" setting is "+12kHz".

73, Wolfgang

**Comment by db4ple** [comment] 2016-04-30 18:41
Fix has been tested (works for me) and merged.
Please report your findings so that we can close the issue or do further work on it.

**Comment by ghost** [comment] 2016-05-01 07:29
The fix works here also.
Therefore, the issue can be closed.
73, Wolfgang

**Closed as completed** 2016-05-01 07:32 UTC
